[2024-01-13T19:45:07.777+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_likes_score.get_data manual__2024-01-13T19:40:02.969071+00:00 [queued]>
[2024-01-13T19:45:07.783+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_likes_score.get_data manual__2024-01-13T19:40:02.969071+00:00 [queued]>
[2024-01-13T19:45:07.784+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-13T19:45:07.799+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): get_data> on 2024-01-13 19:40:02.969071+00:00
[2024-01-13T19:45:07.800+0000] {standard_task_runner.py:60} INFO - Started process 189118 to run task
[2024-01-13T19:45:07.806+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_likes_score', 'get_data', 'manual__2024-01-13T19:40:02.969071+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp2egklge4']
[2024-01-13T19:45:07.808+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask get_data
[2024-01-13T19:45:07.889+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_likes_score.get_data manual__2024-01-13T19:40:02.969071+00:00 [running]> on host prodsrv
[2024-01-13T19:45:08.028+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_likes_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-13T19:40:02.969071+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-13T19:40:02.969071+00:00'
[2024-01-13T19:45:08.029+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-13T19:45:08.029+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/scripts/get_data.py']
[2024-01-13T19:45:08.038+0000] {subprocess.py:86} INFO - Output:
[2024-01-13T19:45:08.051+0000] {subprocess.py:93} INFO - python3: can't open file '/home/scripts/get_data.py': [Errno 2] No such file or directory
[2024-01-13T19:45:08.053+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-01-13T19:45:08.091+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/admin/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/admin/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-01-13T19:45:08.098+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_likes_score, task_id=get_data, execution_date=20240113T194002, start_date=20240113T194507, end_date=20240113T194508
[2024-01-13T19:45:08.133+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task get_data (Bash command failed. The command returned a non-zero exit code 2.; 189118)
[2024-01-13T19:45:08.180+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-13T19:45:08.248+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
